
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umzyfiqvhnnyglchfyzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtenlmaXF2aG5ueWdsY2hmeXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODg0NjMsImV4cCI6MjA1OTA2NDQ2M30.b2HBPjnjVyXXnuCOmYgouI1s8HRQpS51EJdGa2goD3c";

// Import the supabase client like this:
// import { supabase } from "@/Backend/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
